name: flutter_maps
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_maps_flutter: ^0.5.21+15
  splashscreen: ^1.2.0
  location: ^2.3.5
  flutter_launcher_icons: ^0.7.5
  firebase_core: ^0.4.0+9
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
  firebase_database:
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  nice_button: ^0.1.7
  flutter_bounce: ^1.0.8
  connectivity: ^0.3.2
  bottom_navy_bar: ^5.4.0
  image_auto_slider: ^0.0.3
  shared_preferences: ^0.5.7+1
  flutter_responsive_screen: ^1.0.0
  responsive_widgets: ^2.0.1
  page_transition: "^1.1.5"
  bouncing_widget: ^1.2.0
  permission_handler: ^4.0.0
  geolocator: ^5.3.1
  flutter_icons: ^1.1.0
  background_location: ^0.0.9+3
  path_provider: ^1.6.7
  url_launcher: ^5.4.7
  flutter:
    sdk: flutter
# flutter_icons:
#   image_path : "assets/rounded.png"
#   android: true
#   ios: true
#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon-400.png"
  image_path_android: "assets/images/icon-400.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/car_icon.png
    - assets/
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/logo.png
    - assets/images/diagnostic.png
    - img/img11.jpg
    - img/img2.png
    - img/img3.png
    - img/img4.jpg
    - img/img5.jpg
    - img/img6.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic